import './globals.css'
import Link from 'next/link'
export const metadata = {
  title: 'demo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav><Link href="/">Home</Link></nav>
        {children}
      </body>
    </html>
  );
}
